[package]
name = "inference-runtime-service"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
build = "build.rs"

[dependencies]
axum = { workspace = true }
async-channel = { workspace = true }
async-stream = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true, features = ["derive"] }
crossbeam-channel = { workspace = true }
escargot = { workspace = true }
futures-util = { workspace = true }
hf-chat-template = { workspace = true }
hound = { workspace = true }
inference-executor-core = { path = "../inference-executor-core" }
inference-executor-metal = { path = "../inference-executor-metal" }
inference-runtime-core = { path = "../inference-runtime-core" }
inference-runtime-proto = { path = "../inference-runtime-proto" }
mimalloc = { workspace = true }
ordered-float = { workspace = true }
rubato = { workspace = true }
rustfft = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = [
    "macros",
    "rt-multi-thread",
    "sync",
    "time",
] }
tokio-stream = { workspace = true }
tonic = { workspace = true, features = ["transport"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "time"] }
uuid = { workspace = true }

[dev-dependencies]
tokenizers = { workspace = true }
